"""HDFC Bank statement adapter.

Strategy:
  1. Pull header/account metadata and the printed STATEMENT SUMMARY (gives us the
     opening balance to seed the chain, plus figures to cross-check our parse).
  2. Reconstruct every transaction's Dr/Cr from the balance column
     (:func:`pair_by_running_balance`) — this is what guarantees correctness.
  3. Best-effort enrich each transaction with its date, value date, ref (UTR) and a
     cleaned multi-line narration.

Adding another bank later = a sibling module implementing :class:`BankAdapter`; the
running-balance spine in ``base`` is reused unchanged.
"""
from __future__ import annotations

import re
from decimal import Decimal

from core.ingest.base import (
    DATE_LEAD_RE,
    DATE_ONLY_RE,
    MONEY_RE,
    BankAdapter,
    ParseError,
    pair_by_running_balance,
    parse_ddmmyy,
    parse_ddmmyyyy,
    to_decimal,
)
from core.schema import AccountInfo, Statement, Transaction

INT_RE = re.compile(r"^\d+$")

# Line prefixes / constants that repeat as page header+footer boilerplate. Filtered
# only to keep narration clean — correctness never depends on this list.
_BOILER_PREFIXES = (
    "Page No", "M/S.", "JOINT HOLDERS", "Nomination", "Statement of account",
    "From :", "To :", "Account Branch", "Address", "City", "State", "Phone no",
    "OD Limit", "Currency", "Email", "Cust ID", "Account No", "A/C Open Date",
    "Account Status", "RTGS/NEFT IFSC", "MICR", "Branch Code", "Account Type",
    "HDFC BANK LIMITED", "*Closing balance", "Contents of this statement",
    "this statement.", "State account branch GSTN", "HDFC Bank GSTIN",
    "Registered Office Address", "Generated On", "Generated By", "Requesting Branch",
    "This is a computer", "not require signature", "STATEMENT SUMMARY",
    "Opening Balance", "Dr Count", "Cr Count", "Closing Bal", "Date", "Narration",
    "Chq./Ref.No", "Value Dt", "Withdrawal Amt", "Deposit Amt", "Closing Balance",
)
_BOILER_EXACT = {
    "RAMANAYAPET", "KAKINADA", "KAKINADA 533003", "ANDHRA PRADESH INDIA",
    "OPP ASHRAM PUBLIC SCHOOL", "Debits", "Credits",
}


def _is_date(s: str) -> bool:
    return bool(DATE_ONLY_RE.match(s))


def _lead_date(s: str) -> str | None:
    m = DATE_LEAD_RE.match(s)
    return m.group(1) if m else None


def _is_boiler(s: str) -> bool:
    if s.startswith(":"):  # metadata values are printed as ": value"
        return True
    if s in _BOILER_EXACT:
        return True
    if s.startswith("70-"):  # the account address lines
        return True
    return any(s.startswith(p) for p in _BOILER_PREFIXES)


class HDFCAdapter(BankAdapter):
    bank_name = "HDFC"

    @classmethod
    def matches(cls, text: str) -> bool:
        up = text.upper()
        return "HDFC BANK" in up and ("CHQ./REF.NO" in up or "STATEMENT OF ACCOUNT" in up)

    # ---- header / summary -------------------------------------------------
    def _account_info(self, lines: list[str], text: str) -> AccountInfo:
        info = AccountInfo(bank=self.bank_name)

        for i, ln in enumerate(lines):
            if ln == "M/S." and i + 1 < len(lines):
                info.account_name = lines[i + 1].strip()
                break

        m = re.search(r"Account No\s*\n\s*:?\s*(\d{9,20})", text)
        if m:
            info.account_no = m.group(1)
        m = re.search(r"IFSC:\s*([A-Z]{4}0[A-Z0-9]{6})", text)
        if m:
            info.ifsc = m.group(1)
        m = re.search(r"From\s*:\s*(\d{2}/\d{2}/\d{4})", text)
        if m:
            info.from_date = parse_ddmmyyyy(m.group(1))
        m = re.search(r"To\s*:\s*(\d{2}/\d{2}/\d{4})", text)
        if m:
            info.to_date = parse_ddmmyyyy(m.group(1))
        return info

    def _summary(self, lines: list[str]) -> tuple[int, list[str]]:
        """Return (summary_line_index, six-value-tokens). Raises if not found."""
        sidx = next((i for i, ln in enumerate(lines) if ln.startswith("STATEMENT SUMMARY")), None)
        if sidx is None:
            raise ParseError("HDFC: STATEMENT SUMMARY block not found — cannot seed opening balance.")
        nums: list[str] = []
        for ln in lines[sidx:]:
            if MONEY_RE.match(ln) or INT_RE.match(ln):
                nums.append(ln)
            if len(nums) >= 6:
                break
        if len(nums) < 6:
            raise ParseError("HDFC: summary figures incomplete.")
        return sidx, nums[:6]

    # ---- enrichment -------------------------------------------------------
    def _enrich(self, body: list[str], rec, floor_idx: int, row: int) -> Transaction:
        amount_idx = rec.amount_idx
        balance_idx = amount_idx + 1
        value_date_idx = amount_idx - 1
        ref_idx = amount_idx - 2

        value_date = None
        if value_date_idx >= 0 and _is_date(body[value_date_idx]):
            value_date = parse_ddmmyy(body[value_date_idx])

        ref = None
        if ref_idx >= floor_idx and not _is_date(body[ref_idx]) and not MONEY_RE.match(body[ref_idx]):
            ref = body[ref_idx].strip()

        # txn date: nearest lead-date scanning back from the ref line
        txn_date_idx = None
        for i in range(min(ref_idx, value_date_idx - 1), floor_idx - 1, -1):
            if _lead_date(body[i]):
                txn_date_idx = i
                break
        if txn_date_idx is None:
            txn_date = value_date
            part_a = ""
            hi = value_date_idx
            lo = value_date_idx
        else:
            txn_date = parse_ddmmyy(_lead_date(body[txn_date_idx]))
            part_a = body[txn_date_idx][8:].strip()  # text after 'dd/mm/yy'
            lo = txn_date_idx
            hi = ref_idx if ref is not None else value_date_idx

        # narration between the date line and the ref line
        mid = []
        for i in range(lo + 1, hi):
            s = body[i]
            if _is_date(s) or MONEY_RE.match(s) or _is_boiler(s):
                continue
            mid.append(s)

        # narration continuation immediately after the balance line
        tail = []
        i = balance_idx + 1
        while i < len(body) and len(tail) < 4:
            s = body[i]
            if _lead_date(s) or MONEY_RE.match(s) or _is_boiler(s):
                break
            tail.append(s)
            i += 1

        narration = re.sub(r"\s+", " ", " ".join(x for x in [part_a, *mid, *tail] if x)).strip()
        if txn_date is None:  # safety net; should not happen on HDFC
            raise ParseError(f"HDFC: could not resolve transaction date near line {amount_idx}.")

        return Transaction(
            row=row,
            txn_date=txn_date,
            value_date=value_date,
            narration=narration,
            ref_no=ref,
            amount=rec.amount,
            dr_cr=rec.dr_cr,
            balance=rec.balance,
        )

    # ---- main -------------------------------------------------------------
    def parse(self, text: str) -> Statement:
        lines = [ln.strip() for ln in text.split("\n") if ln.strip()]
        info = self._account_info(lines, text)
        sidx, snums = self._summary(lines)

        info.opening_balance = to_decimal(snums[0])
        info.stmt_dr_count = int(snums[1])
        info.stmt_cr_count = int(snums[2])
        info.stmt_total_debits = to_decimal(snums[3])
        info.stmt_total_credits = to_decimal(snums[4])
        info.closing_balance = to_decimal(snums[5])

        # Parse transactions only from the body above the summary block.
        body = lines[:sidx]
        tokens = [(i, to_decimal(s)) for i, s in enumerate(body) if MONEY_RE.match(s)]
        records, _final = pair_by_running_balance(tokens, info.opening_balance)

        txns: list[Transaction] = []
        prev_balance_idx = -1
        for k, rec in enumerate(records):
            floor_idx = prev_balance_idx + 1
            txns.append(self._enrich(body, rec, floor_idx, row=k + 1))
            prev_balance_idx = rec.amount_idx + 1

        return Statement(info=info, transactions=txns)
