"""Excel working-paper generator — the audit-ready deliverable.

Produces a multi-sheet workbook (Cover, Reconciliation, Transactions, Ledger Summary,
Exceptions) formatted so it can drop straight into an auditor's file. Returns raw
bytes so the Streamlit layer (or a future API) can offer it as a download.
"""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from core.schema import DrCr, ExceptionFlag, ReconResult, Statement

MONEY_FMT = "#,##0.00"
_HEADER_FILL = PatternFill("solid", fgColor="1F4E78")
_HEADER_FONT = Font(bold=True, color="FFFFFF")
_TITLE_FONT = Font(bold=True, size=14, color="1F4E78")
_SEV_FILL = {
    "high": PatternFill("solid", fgColor="F8CBAD"),
    "medium": PatternFill("solid", fgColor="FFE699"),
    "low": PatternFill("solid", fgColor="D9E1F2"),
}
_THIN = Side(style="thin", color="BFBFBF")
_BORDER = Border(left=_THIN, right=_THIN, top=_THIN, bottom=_THIN)


def _header_row(ws, headers, row=1):
    for c, h in enumerate(headers, start=1):
        cell = ws.cell(row=row, column=c, value=h)
        cell.fill = _HEADER_FILL
        cell.font = _HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = _BORDER
    ws.freeze_panes = ws.cell(row=row + 1, column=1)


def _widths(ws, widths):
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w


def _kv(ws, r, label, value, money=False):
    ws.cell(row=r, column=1, value=label).font = Font(bold=True)
    cell = ws.cell(row=r, column=2, value=value)
    if money and isinstance(value, Decimal):
        cell.number_format = MONEY_FMT
    return r + 1


def _cover(wb, st, recon, flags, stats):
    ws = wb.active
    ws.title = "Cover"
    ws["A1"] = "AuditWedge — Bank Statement Working Paper"
    ws["A1"].font = _TITLE_FONT
    info = st.info
    r = 3
    r = _kv(ws, r, "Client", info.account_name)
    r = _kv(ws, r, "Bank", info.bank)
    r = _kv(ws, r, "Account No", info.account_no)
    r = _kv(ws, r, "IFSC", info.ifsc)
    r = _kv(ws, r, "Period", f"{info.from_date}  to  {info.to_date}")
    r += 1
    r = _kv(ws, r, "Opening Balance", recon.opening_balance, money=True)
    r = _kv(ws, r, "Closing Balance (computed)", recon.closing_balance_computed, money=True)
    r = _kv(ws, r, "Closing Balance (bank)", recon.closing_balance_reported, money=True)
    r = _kv(ws, r, "Balance chain integrity", "OK — zero drift" if recon.balance_chains else "CHECK")
    r = _kv(ws, r, "Ties to bank summary", {True: "Yes", False: "No", None: "n/a"}[recon.matches_statement_summary])
    r += 1
    r = _kv(ws, r, "Transactions", len(st.transactions))
    r = _kv(ws, r, "Debits", f"{recon.dr_count}  (Rs {recon.total_debits:,.2f})")
    r = _kv(ws, r, "Credits", f"{recon.cr_count}  (Rs {recon.total_credits:,.2f})")
    r = _kv(ws, r, "Auto-classified", f"{stats['classified']} of {stats['total']}  ({stats['rate']*100:.0f}%)")
    r = _kv(ws, r, "Need manual review", stats["needs_review"])
    r += 1
    highs = sum(1 for f in flags if f.severity.value == "high")
    meds = sum(1 for f in flags if f.severity.value == "medium")
    lows = sum(1 for f in flags if f.severity.value == "low")
    r = _kv(ws, r, "Exceptions raised", f"{len(flags)}   (High {highs} / Medium {meds} / Low {lows})")
    r += 1
    ws.cell(row=r, column=1, value=f"Generated by AuditWedge on {datetime.now():%d-%b-%Y %H:%M}. "
            f"Draft — subject to auditor review and sign-off.").font = Font(italic=True, color="808080")
    _widths(ws, [30, 55])


def _reconciliation(wb, recon):
    ws = wb.create_sheet("Reconciliation")
    ws["A1"] = "Bank Reconciliation"
    ws["A1"].font = _TITLE_FONT
    r = 3
    r = _kv(ws, r, "Opening balance", recon.opening_balance, money=True)
    r = _kv(ws, r, "Add: Total credits", recon.total_credits, money=True)
    r = _kv(ws, r, "Less: Total debits", recon.total_debits, money=True)
    r = _kv(ws, r, "Computed closing balance", recon.closing_balance_computed, money=True)
    r = _kv(ws, r, "Closing per bank", recon.closing_balance_reported, money=True)
    r = _kv(ws, r, "Max balance-chain drift", recon.max_drift, money=True)
    r += 1
    ws.cell(row=r, column=1, value="Notes:").font = Font(bold=True)
    for note in recon.notes:
        r += 1
        ws.cell(row=r, column=1, value="• " + note)
    _widths(ws, [30, 30])


def _transactions(wb, st):
    ws = wb.create_sheet("Transactions")
    headers = ["#", "Date", "Value Dt", "Narration", "Ref / UTR", "Debit", "Credit",
               "Balance", "Ledger", "Counterparty", "Type", "Conf.", "Source"]
    _header_row(ws, headers)
    for i, t in enumerate(st.transactions, start=2):
        ws.cell(row=i, column=1, value=t.row)
        ws.cell(row=i, column=2, value=t.txn_date.isoformat())
        ws.cell(row=i, column=3, value=t.value_date.isoformat() if t.value_date else "")
        ws.cell(row=i, column=4, value=t.narration)
        ws.cell(row=i, column=5, value=t.ref_no or "")
        dr = ws.cell(row=i, column=6, value=float(t.amount) if t.dr_cr is DrCr.DEBIT else None)
        cr = ws.cell(row=i, column=7, value=float(t.amount) if t.dr_cr is DrCr.CREDIT else None)
        bal = ws.cell(row=i, column=8, value=float(t.balance))
        for cell in (dr, cr, bal):
            cell.number_format = MONEY_FMT
        ws.cell(row=i, column=9, value=t.ledger)
        ws.cell(row=i, column=10, value=t.counterparty or "")
        ws.cell(row=i, column=11, value=t.counterparty_type or "")
        ws.cell(row=i, column=12, value=round(t.confidence, 2))
        ws.cell(row=i, column=13, value=t.source)
    _widths(ws, [5, 11, 10, 52, 20, 12, 12, 12, 22, 26, 12, 7, 12])


def _ledger_summary(wb, st):
    ws = wb.create_sheet("Ledger Summary")
    _header_row(ws, ["Ledger", "Category", "# Txns", "Debit Total", "Credit Total"])
    agg: dict[str, list] = {}
    for t in st.transactions:
        a = agg.setdefault(t.ledger, [t.category, 0, Decimal("0"), Decimal("0")])
        a[1] += 1
        if t.dr_cr is DrCr.DEBIT:
            a[2] += t.amount
        else:
            a[3] += t.amount
    r = 2
    for ledger, (cat, n, dr, cr) in sorted(agg.items(), key=lambda x: -(x[1][2] + x[1][3])):
        ws.cell(row=r, column=1, value=ledger)
        ws.cell(row=r, column=2, value=cat)
        ws.cell(row=r, column=3, value=n)
        d = ws.cell(row=r, column=4, value=float(dr))
        c = ws.cell(row=r, column=5, value=float(cr))
        for cell in (d, c):
            cell.number_format = MONEY_FMT
        r += 1
    _widths(ws, [26, 26, 9, 15, 15])


def _exceptions(wb, flags: list[ExceptionFlag]):
    ws = wb.create_sheet("Exceptions")
    _header_row(ws, ["Severity", "Code", "Finding", "Amount", "Date", "Txn #", "Detail / Action"])
    for i, f in enumerate(flags, start=2):
        sev = ws.cell(row=i, column=1, value=f.severity.value.upper())
        sev.fill = _SEV_FILL.get(f.severity.value, _SEV_FILL["low"])
        sev.font = Font(bold=True)
        ws.cell(row=i, column=2, value=f.code)
        ws.cell(row=i, column=3, value=f.title)
        amt = ws.cell(row=i, column=4, value=float(f.amount) if f.amount is not None else None)
        amt.number_format = MONEY_FMT
        ws.cell(row=i, column=5, value=f.txn_date.isoformat() if f.txn_date else "")
        ws.cell(row=i, column=6, value=f.row if f.row else "")
        d = ws.cell(row=i, column=7, value=f.detail)
        d.alignment = Alignment(wrap_text=True, vertical="top")
    _widths(ws, [10, 22, 34, 13, 11, 7, 70])


def _summary_sheet(wb, s):
    ws = wb.create_sheet("Summary")
    ws["A1"] = "Summary — Receipts / Payments / Turnover / GST"
    ws["A1"].font = _TITLE_FONT
    r = 3
    ws.cell(row=r, column=1, value="RECEIPTS").font = Font(bold=True); r += 1
    for lbl, v in [("Business Receipts (Sundry Debtors)", s.biz_receipts),
                   ("Suspense Receipts", s.sus_receipts), ("Total Receipts", s.total_receipts)]:
        r = _kv(ws, r, lbl, v, money=True)
    r += 1
    ws.cell(row=r, column=1, value="PAYMENTS").font = Font(bold=True); r += 1
    for lbl, v in [("Business Payments (Sundry Creditors)", s.biz_payments),
                   ("Suspense Payments", s.sus_payments), ("Bank Charges", s.charges),
                   ("Total Payments", s.total_payments)]:
        r = _kv(ws, r, lbl, v, money=True)
    r += 1
    ws.cell(row=r, column=1, value="TURNOVER & GST (both treatments)").font = Font(bold=True); r += 1
    for lbl, v in [("GST Turnover — cab (masters)", s.gst_turnover),
                   ("Statement Turnover (gross receipts)", s.stmt_turnover),
                   ("GST — Cab Services @ 5%", s.gst_cab),
                   ("Commission income (masters)", s.commission_base),
                   ("GST — Commission @ 18%", s.gst_commission)]:
        r = _kv(ws, r, lbl, v, money=True)
    r += 1
    for n in s.notes:
        ws.cell(row=r, column=1, value="• " + n).font = Font(italic=True, color="808080"); r += 1
    _widths(ws, [42, 20])


def _two_sided(ws, title, left_groups, right_groups, left_tail=None):
    ws["A1"] = title
    ws["A1"].font = _TITLE_FONT
    for col, h in [(1, "Particulars"), (2, "Amount"), (4, "Particulars"), (5, "Amount")]:
        c = ws.cell(row=3, column=col, value=h); c.fill = _HEADER_FILL; c.font = _HEADER_FONT

    def emit(groups, base_col, tail):
        r = 4
        for gname, lines in groups:
            ws.cell(row=r, column=base_col, value=gname).font = Font(bold=True)
            gt = ws.cell(row=r, column=base_col + 1,
                         value=float(sum(a for _, a in lines))); gt.number_format = MONEY_FMT
            gt.font = Font(bold=True); r += 1
            for name, amt in lines:
                ws.cell(row=r, column=base_col, value="    " + name)
                c = ws.cell(row=r, column=base_col + 1, value=float(amt)); c.number_format = MONEY_FMT
                r += 1
        if tail:
            for name, amt in tail:
                ws.cell(row=r, column=base_col, value=name).font = Font(bold=True)
                c = ws.cell(row=r, column=base_col + 1, value=float(amt)); c.number_format = MONEY_FMT
                c.font = Font(bold=True); r += 1
        return r

    lr = emit(left_groups, 1, left_tail)
    rr = emit(right_groups, 4, None)
    tr = max(lr, rr) + 1
    lt = sum(a for _, ls in left_groups for _, a in ls) + sum(a for _, a in (left_tail or []))
    rt = sum(a for _, ls in right_groups for _, a in ls)
    for col, tot in [(1, lt), (2, lt), (4, rt), (5, rt)]:
        if col in (1, 4):
            ws.cell(row=tr, column=col, value="Total").font = Font(bold=True)
        else:
            c = ws.cell(row=tr, column=col, value=float(tot)); c.number_format = MONEY_FMT
            c.font = Font(bold=True)
    _widths(ws, [34, 15, 3, 34, 15])


def _group(lines):
    """[(group, ledger, amount)] -> [(group, [(ledger, amount)])] preserving order."""
    out, seen = [], {}
    for gr, led, amt in lines:
        if gr not in seen:
            seen[gr] = []
            out.append((gr, seen[gr]))
        seen[gr].append((led, amt))
    return out


def _pnl_sheet(wb, p):
    ws = wb.create_sheet("Profit & Loss")
    exp = _group([(l.group, l.ledger, l.amount) for l in p.expenses])
    inc = _group([(l.group, l.ledger, l.amount) for l in p.income])
    _two_sided(ws, "Profit & Loss A/c", exp, inc, left_tail=[("Nett Profit", p.net_profit)])


def _bs_sheet(wb, b):
    ws = wb.create_sheet("Balance Sheet")
    liab = _group([(l.group, l.ledger, l.amount) for l in b.liabilities])
    asset = _group([(l.group, l.ledger, l.amount) for l in b.assets])
    _two_sided(ws, "Balance Sheet", liab, asset)


def _crosscheck_sheet(wb, checks):
    ws = wb.create_sheet("Cross-checks")
    _header_row(ws, ["Item", "Bank / Invoice", "Books (masters)", "Status"])
    for i, cc in enumerate(checks, start=2):
        ws.cell(row=i, column=1, value=cc.item)
        c = ws.cell(row=i, column=2, value=float(cc.bank_or_invoice)); c.number_format = MONEY_FMT
        if cc.masters is not None:
            m = ws.cell(row=i, column=3, value=float(cc.masters)); m.number_format = MONEY_FMT
        s = ws.cell(row=i, column=4, value=cc.status)
        if "review" in cc.status:
            s.fill = _SEV_FILL["medium"]
    _widths(ws, [34, 16, 16, 24])


def _gst_sheet(wb, gst):
    ws = wb.create_sheet("GST")
    ws["A1"] = "GST — computation (both treatments)"
    ws["A1"].font = _TITLE_FONT
    r = _kv(ws, 3, "GSTIN", gst.gstin)
    r = _kv(ws, r, "Return period (MMYYYY)", gst.ret_period)
    r = _kv(ws, r, "Supply type", "Intra-state (CGST+SGST)" if gst.intra_state else "Inter-state (IGST)")
    r += 1
    _header_row(ws, ["Treatment", "Taxable", "Rate %", "IGST", "CGST", "SGST", "Total tax"], row=r)
    r += 1
    for sc in (gst.cab, gst.commission):
        ws.cell(row=r, column=1, value=sc.label)
        for c, v in enumerate([sc.taxable, sc.rate, sc.igst, sc.cgst, sc.sgst, sc.total_tax], start=2):
            cell = ws.cell(row=r, column=c, value=float(v))
            if c != 3:
                cell.number_format = MONEY_FMT
        r += 1
    _widths(ws, [40, 15, 8, 13, 13, 13, 14])


def _itr_sheet(wb, itr):
    ws = wb.create_sheet("ITR figures")
    ws["A1"] = f"ITR figures — {itr.form}, AY {itr.assessment_year}"
    ws["A1"].font = _TITLE_FONT
    r = 3
    for title, d in [("Profit & Loss schedule", itr.pl), ("Balance Sheet schedule", itr.bs),
                     ("Computation of income & tax", itr.computation)]:
        ws.cell(row=r, column=1, value=title).font = Font(bold=True)
        r += 1
        for k, v in d.items():
            label = k.replace("_", " ").title()
            if isinstance(v, (int, float)):
                r = _kv(ws, r, label, float(v), money=True)
            else:
                r = _kv(ws, r, label, str(v))
        r += 1
    _widths(ws, [40, 22])


def build_workpaper(st: Statement, recon: ReconResult, flags: list[ExceptionFlag], stats: dict,
                    financials=None, gst=None, itr=None) -> bytes:
    wb = Workbook()
    _cover(wb, st, recon, flags, stats)
    if financials is not None:
        _summary_sheet(wb, financials.summary)
        _pnl_sheet(wb, financials.pnl)
        _bs_sheet(wb, financials.balance_sheet)
        _crosscheck_sheet(wb, financials.cross_checks)
    if gst is not None:
        _gst_sheet(wb, gst)
    if itr is not None:
        _itr_sheet(wb, itr)
    _reconciliation(wb, recon)
    _transactions(wb, st)
    _ledger_summary(wb, st)
    _exceptions(wb, flags)
    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()
