"""Excel working-paper generator — the audit-ready deliverable.

Produces a multi-sheet workbook (Cover, Reconciliation, Transactions, Ledger Summary,
Exceptions) formatted so it can drop straight into an auditor's file. Returns raw
bytes so the Streamlit layer (or a future API) can offer it as a download.
"""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from core.schema import DrCr, ExceptionFlag, ReconResult, Statement

MONEY_FMT = "#,##0.00"
_HEADER_FILL = PatternFill("solid", fgColor="1F4E78")
_HEADER_FONT = Font(bold=True, color="FFFFFF")
_TITLE_FONT = Font(bold=True, size=14, color="1F4E78")
_SEV_FILL = {
    "high": PatternFill("solid", fgColor="F8CBAD"),
    "medium": PatternFill("solid", fgColor="FFE699"),
    "low": PatternFill("solid", fgColor="D9E1F2"),
}
_THIN = Side(style="thin", color="BFBFBF")
_BORDER = Border(left=_THIN, right=_THIN, top=_THIN, bottom=_THIN)


def _header_row(ws, headers, row=1):
    for c, h in enumerate(headers, start=1):
        cell = ws.cell(row=row, column=c, value=h)
        cell.fill = _HEADER_FILL
        cell.font = _HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = _BORDER
    ws.freeze_panes = ws.cell(row=row + 1, column=1)


def _widths(ws, widths):
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w


def _kv(ws, r, label, value, money=False):
    ws.cell(row=r, column=1, value=label).font = Font(bold=True)
    cell = ws.cell(row=r, column=2, value=value)
    if money and isinstance(value, Decimal):
        cell.number_format = MONEY_FMT
    return r + 1


def _cover(wb, st, recon, flags, stats):
    ws = wb.active
    ws.title = "Cover"
    ws["A1"] = "AuditWedge — Bank Statement Working Paper"
    ws["A1"].font = _TITLE_FONT
    info = st.info
    r = 3
    r = _kv(ws, r, "Client", info.account_name)
    r = _kv(ws, r, "Bank", info.bank)
    r = _kv(ws, r, "Account No", info.account_no)
    r = _kv(ws, r, "IFSC", info.ifsc)
    r = _kv(ws, r, "Period", f"{info.from_date}  to  {info.to_date}")
    r += 1
    r = _kv(ws, r, "Opening Balance", recon.opening_balance, money=True)
    r = _kv(ws, r, "Closing Balance (computed)", recon.closing_balance_computed, money=True)
    r = _kv(ws, r, "Closing Balance (bank)", recon.closing_balance_reported, money=True)
    r = _kv(ws, r, "Balance chain integrity", "OK — zero drift" if recon.balance_chains else "CHECK")
    r = _kv(ws, r, "Ties to bank summary", {True: "Yes", False: "No", None: "n/a"}[recon.matches_statement_summary])
    r += 1
    r = _kv(ws, r, "Transactions", len(st.transactions))
    r = _kv(ws, r, "Debits", f"{recon.dr_count}  (Rs {recon.total_debits:,.2f})")
    r = _kv(ws, r, "Credits", f"{recon.cr_count}  (Rs {recon.total_credits:,.2f})")
    r = _kv(ws, r, "Auto-classified", f"{stats['classified']} of {stats['total']}  ({stats['rate']*100:.0f}%)")
    r = _kv(ws, r, "Need manual review", stats["needs_review"])
    r += 1
    highs = sum(1 for f in flags if f.severity.value == "high")
    meds = sum(1 for f in flags if f.severity.value == "medium")
    lows = sum(1 for f in flags if f.severity.value == "low")
    r = _kv(ws, r, "Exceptions raised", f"{len(flags)}   (High {highs} / Medium {meds} / Low {lows})")
    r += 1
    ws.cell(row=r, column=1, value=f"Generated by AuditWedge on {datetime.now():%d-%b-%Y %H:%M}. "
            f"Draft — subject to auditor review and sign-off.").font = Font(italic=True, color="808080")
    _widths(ws, [30, 55])


def _reconciliation(wb, recon):
    ws = wb.create_sheet("Reconciliation")
    ws["A1"] = "Bank Reconciliation"
    ws["A1"].font = _TITLE_FONT
    r = 3
    r = _kv(ws, r, "Opening balance", recon.opening_balance, money=True)
    r = _kv(ws, r, "Add: Total credits", recon.total_credits, money=True)
    r = _kv(ws, r, "Less: Total debits", recon.total_debits, money=True)
    r = _kv(ws, r, "Computed closing balance", recon.closing_balance_computed, money=True)
    r = _kv(ws, r, "Closing per bank", recon.closing_balance_reported, money=True)
    r = _kv(ws, r, "Max balance-chain drift", recon.max_drift, money=True)
    r += 1
    ws.cell(row=r, column=1, value="Notes:").font = Font(bold=True)
    for note in recon.notes:
        r += 1
        ws.cell(row=r, column=1, value="• " + note)
    _widths(ws, [30, 30])


def _transactions(wb, st):
    ws = wb.create_sheet("Transactions")
    headers = ["#", "Date", "Value Dt", "Narration", "Ref / UTR", "Debit", "Credit",
               "Balance", "Ledger", "Counterparty", "Type", "Conf.", "Source"]
    _header_row(ws, headers)
    for i, t in enumerate(st.transactions, start=2):
        ws.cell(row=i, column=1, value=t.row)
        ws.cell(row=i, column=2, value=t.txn_date.isoformat())
        ws.cell(row=i, column=3, value=t.value_date.isoformat() if t.value_date else "")
        ws.cell(row=i, column=4, value=t.narration)
        ws.cell(row=i, column=5, value=t.ref_no or "")
        dr = ws.cell(row=i, column=6, value=float(t.amount) if t.dr_cr is DrCr.DEBIT else None)
        cr = ws.cell(row=i, column=7, value=float(t.amount) if t.dr_cr is DrCr.CREDIT else None)
        bal = ws.cell(row=i, column=8, value=float(t.balance))
        for cell in (dr, cr, bal):
            cell.number_format = MONEY_FMT
        ws.cell(row=i, column=9, value=t.ledger)
        ws.cell(row=i, column=10, value=t.counterparty or "")
        ws.cell(row=i, column=11, value=t.counterparty_type or "")
        ws.cell(row=i, column=12, value=round(t.confidence, 2))
        ws.cell(row=i, column=13, value=t.source)
    _widths(ws, [5, 11, 10, 52, 20, 12, 12, 12, 22, 26, 12, 7, 12])


def _ledger_summary(wb, st):
    ws = wb.create_sheet("Ledger Summary")
    _header_row(ws, ["Ledger", "Category", "# Txns", "Debit Total", "Credit Total"])
    agg: dict[str, list] = {}
    for t in st.transactions:
        a = agg.setdefault(t.ledger, [t.category, 0, Decimal("0"), Decimal("0")])
        a[1] += 1
        if t.dr_cr is DrCr.DEBIT:
            a[2] += t.amount
        else:
            a[3] += t.amount
    r = 2
    for ledger, (cat, n, dr, cr) in sorted(agg.items(), key=lambda x: -(x[1][2] + x[1][3])):
        ws.cell(row=r, column=1, value=ledger)
        ws.cell(row=r, column=2, value=cat)
        ws.cell(row=r, column=3, value=n)
        d = ws.cell(row=r, column=4, value=float(dr))
        c = ws.cell(row=r, column=5, value=float(cr))
        for cell in (d, c):
            cell.number_format = MONEY_FMT
        r += 1
    _widths(ws, [26, 26, 9, 15, 15])


def _exceptions(wb, flags: list[ExceptionFlag]):
    ws = wb.create_sheet("Exceptions")
    _header_row(ws, ["Severity", "Code", "Finding", "Amount", "Date", "Txn #", "Detail / Action"])
    for i, f in enumerate(flags, start=2):
        sev = ws.cell(row=i, column=1, value=f.severity.value.upper())
        sev.fill = _SEV_FILL.get(f.severity.value, _SEV_FILL["low"])
        sev.font = Font(bold=True)
        ws.cell(row=i, column=2, value=f.code)
        ws.cell(row=i, column=3, value=f.title)
        amt = ws.cell(row=i, column=4, value=float(f.amount) if f.amount is not None else None)
        amt.number_format = MONEY_FMT
        ws.cell(row=i, column=5, value=f.txn_date.isoformat() if f.txn_date else "")
        ws.cell(row=i, column=6, value=f.row if f.row else "")
        d = ws.cell(row=i, column=7, value=f.detail)
        d.alignment = Alignment(wrap_text=True, vertical="top")
    _widths(ws, [10, 22, 34, 13, 11, 7, 70])


def build_workpaper(st: Statement, recon: ReconResult, flags: list[ExceptionFlag], stats: dict) -> bytes:
    wb = Workbook()
    _cover(wb, st, recon, flags, stats)
    _reconciliation(wb, recon)
    _transactions(wb, st)
    _ledger_summary(wb, st)
    _exceptions(wb, flags)
    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()
